Controller:
  LeaderElectionNamespace: # TODO: Set namespace
  TokenKeyNamespace: # TODO: Set namespace

ExtAuthz:
  ClusterName: istio-oidc
  Timeout: 1h

Replication:
  AdvertiseAddress: # TODO: Set your IP and port here

Keycloak:
  URL: # TODO: Set Keycloak URL
