# Configures Istio to preform ExtAuthz with locally running application
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  configPatches:
  # Insert cluster referencing locally running application being debugged
  - applyTo: CLUSTER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        name: ext-authz
        connect_timeout: 1s
        load_assignment:
          cluster_name: ext-authz
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.170.1.200
                    port_value: 8082
        http2_protocol_options: {}

  # Insert ExtAuthz filter
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
          grpc_service:
            envoy_grpc:
              cluster_name: ext-authz
            timeout: 86400s

  # Insert ExtAuthz disable config for all virtual hosts
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.ext_authz:
            '@type': type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthzPerRoute
            disabled: true

  # Insert ExtAuthz root config for targeted virtual host
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration: # TODO: Why doesn't gateway work here?
        vhost:
          name: jaeger.localhost:80
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.ext_authz:
            '@type': type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthzPerRoute
            check_settings:
              context_extensions:
                service: jaeger

  # Insert ExtAuthz config for route
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: jaeger.localhost:80
          route:
            name: root
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.ext_authz:
            '@type': type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthzPerRoute
            check_settings:
              context_extensions:
                roles: Fv+DBAEBBVJvbGVzAf+EAAEMAf+CAAAM/4ECAQL/ggABDAAAGf+EAAIAAQZnbG9iYWwEdGVzdAEFbG9jYWw=