apiVersion: krsdev.app/v1
kind: OpenIDProvider
metadata:
  name: debug
spec:
  issuer: # TODO: Set issuer
---
apiVersion: krsdev.app/v1
kind: AccessPolicy
metadata:
  name: debug
spec:
  gateway: # TODO: Set gateway
  oidc:
    provider: debug
    credentialsSecretRef:
      name: debug
---
apiVersion: v1
kind: Secret
metadata:
  name: debug
stringData:
  clientID: # TODO: Set client ID
  clientSecret: # TODO: Set client secret
